# Cloudflare Pages 配置文件
name = "heysss1-surf-spots"
compatibility_date = "2024-08-19"

[build]
command = "cd client && npm install && npm run build"
cwd = "."
publish = "client/build"

# 环境变量
[env.production.vars]
REACT_APP_API_URL = "https://heysss1.com/api"